### ISSUE TITLE
There is a typo in library yoooooo word gets printed along with library

### ISSUE THREAD

**Issue by vishaltambe70** [plotly/dash-alternative-viz#13]
![typo](https://user-images.githubusercontent.com/54836274/136380534-de37aef9-1eb6-44d6-89b7-a8c6d86d4197.png)

at left top corner typo yooooooo is present , will you please help me regarding that

**Comment by sanjaymeena** [comment]
> I am also getting this issue on every HighCharts component I include in my app. The text 'yoooooo' appears in the top left corner of every chart. Bokeh charts and SVG appear to be fine, the issue is solely with Highcharts.
> 
> Does anyone have any suggestions on how to fix this issue?
> 
> ### Example of the issue below:
> ![image](https://user-images.githubusercontent.com/36100849/155694936-031642dc-01ca-4f2b-98f7-973df118410b.png)
> 
> ```
> 
> import dash
> from dash import html
> import dash_alternative_viz as dav
> 
> chart_options = {
>     'series':[{
>         'data': [
>     [100, 240, 3],
>     [200, 130, 10],
>     [450, 290, 15]
>         ]
>     }]
> }
> 
> 
> app = dash.Dash()
> 
> app.layout = html.Div(dav.HighChart(id='test_chart', options=chart_options))
> 
> if __name__ == '__main__':
>     app.run_server(debug=False)
> ```

It will be great if this issue is fixed!

**Comment by lukeallpress** [comment]
I haven't actually played around with it, but you can find the string `yoooooo` in the dash_alternative_viz.dev.js file. Assume deleting that should fix the output.

**Comment by nicolaskruchten** [comment]
I don't recommend you use the code from `master` in this repo, rather folks should use the tarball in the 0.0.1 release: https://github.com/plotly/dash-alternative-viz/releases/tag/v0.0.1

**Comment by nicolaskruchten** [comment]
That said, I've just updated the bundles on master to remove this debugging string :)

**Comment by emyrr** [comment]
> That said, I've just updated the bundles on master to remove this debugging string :)

Perfect, thanks Luke and Nicolas for your help!
